---
title: Redirects with netlify
author: ''
date: '2020-01-23'
slug: redirects-with-netlify
categories: [netlify]
tags: [netlify, redirects]
---

<!-- Twitter post formatting script -->
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

I recently saw this tweet from [Danielle Navarro](https://djnavarro.net) about
purchasing a domain to serve redirects to important links.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Possibly the most ridiculous thing I&#39;ve spent $14/year on... buying <a href="https://djnavarro.link">djnavarro.link</a> so that I can have my own personal link shortening service. Because <a href="https://djnavarro.link/scholar">djnavarro.link/scholar</a><br><br>is a much nicer link to my Google Scholar profile and at least I can remember the damn thing</p>&mdash; Danielle Navarro (@djnavarro) <a href="https://twitter.com/djnavarro/status/1219867040946589698?ref_src=twsrc%5Etfw">January 22, 2020</a></blockquote> 

What a great idea!
I'm pretty sure I will never memorize
https://orcid.org/0000-0002-4648-654X, so it would be nice to have something
easier to share.
But, I don't want to purchase a separate domain.
`r emoji("money_with_wings", "sob")`

Fear not, [Rob J Hyndman](https://robjhyndman.com) notes that netlify has an
easy way to setup redirects from your domain!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I think netlify can do something similar. See <a href="https://docs.netlify.com/routing/redirects">docs.netlify.com/routing/redirects</a></p>&mdash; Rob J Hyndman (@robjhyndman) <a href="https://twitter.com/robjhyndman/status/1219880800935501824?ref_src=twsrc%5Etfw">January 22, 2020</a></blockquote>

Let's see if I can get this to work!
According to the netlify documentation, there are two ways to do redirects.
One is fairly simple, but less powerful.
I like simple, so I'll go with that.

Here are the steps:

1. Create the following file: `static/_redirects`
2. Fill it with urls like so:

    ```
    # Redirect from yourdomain.com*, to url
    /orcid        https://orcid.org/0000-0002-4648-654X
    /researchgate https://www.researchgate.net/profile/Eric_Bryant
    /twitter      https://twitter.com/EricBryantPhD
    /github       https://github.com/EricBryantPhD
    ```

Now, I can share my ORCID profile with
[ericbryantphd.com/orcid](https://ericbryantphd.com/orcid).
`r emoji("partying_face")`

Of course, the downside of this is that it isn't really clear that these links
will redirect, which is not very transparent (i.e. kinda rude actually) as
noted by Danielle:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I kind of like it. I really like the fact that there&#39;s some transparency to the process because it&#39;s a .link domain. <br><br>Anything at <a href="https://djnavarro.net">djnavarro.net</a> is my own website, anything at <a href="https://djnavarro.link">djnavarro.link</a> goes elsewhere `r emoji("slightly_smiling_face")`</p>&mdash; Danielle Navarro (@djnavarro) <a href="https://twitter.com/djnavarro/status/1220086435295793152?ref_src=twsrc%5Etfw">January 22, 2020</a></blockquote>

For this use case though, I think it is fairly clear that e.g.
[ericbryantphd.com/orcid](https://ericbryantphd.com/orcid) will take you to a
page having something to do with ORCID, and e.g.
[ericbryantphd.com/github](https://ericbryantphd.com/github) will take you to 
a page having something to do with GitHub, so I'm sticking to it!
